### ISSUE TITLE
Segments data missing

### ISSUE THREAD

**Issue by Aricling** [LvXinTao/HIMO_dataset#6]
After acquring the link to HIMO_Dataset, I observed that there are only 5 .zip files.
<img width="319" alt="image" src="https://github.com/user-attachments/assets/fa975676-c330-4476-9dc0-53b349fbf75d">
However, according to the paper, fine-grained segment of the dataset is made. I also saw it in the README, there are 6 dirs in total.
<img width="249" alt="image" src="https://github.com/user-attachments/assets/adbdbcc7-a845-4b76-accf-6c84a41520ae">
Would you mind uploading the segment data too? Thanks a lot!

**Comment by shydyl** [comment]
+1

**Comment by liangxuy** [comment]
Sorry for the delay. We have released the processed data, please refer to https://github.com/LvXinTao/HIMO_dataset?tab=readme-ov-file#news.

**Comment by fansiyuan2019** [comment]
Thanks for the great work! It seems that the segment data is still missing in the provided data. Could you please provide these files?
